--SELECT * FROM book;
--
--desc book;
--SEQUENCE.sql 구 book 테이블 정보
--book 테이블 생성
CREATE TABLE book (
book_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
title VARCHAR2(200) NOT NULL,
author VARCHAR2(100) NOT NULL,
publisher VARCHAR2(100) NOT NULL,
publisher_date DATE NOT NULL,
price NUMBER(10) NOT NULL,
CONSTRAINT book_pk PRIMARY KEY(book_id)
);
--책번호 책제목
--저자
--출판사
--출간일
--책가격

INSERT INTO BOOK (TITLE, AUTHOR, PUBLISHER, PUBLISHER_DATE, PRICE) VALUES 
('해리 포터와 마법사의 돌', 'J.K. 롤링', '문학수첩', TO_DATE('2000-07-01', 'YYYY-MM-DD'), 15000);
INSERT INTO BOOK (TITLE, AUTHOR, PUBLISHER, PUBLISHER_DATE, PRICE) VALUES 
('데미안', '헤르만 헤세', '열린책들', TO_DATE('2010-03-15', 'YYYY-MM-DD'), 12000);
INSERT INTO BOOK (TITLE, AUTHOR, PUBLISHER, PUBLISHER_DATE, PRICE) VALUES 
('1984', '조지 오웰', '민음사', TO_DATE('2008-06-08', 'YYYY-MM-DD'), 13000);
INSERT INTO BOOK (TITLE, AUTHOR, PUBLISHER, PUBLISHER_DATE, PRICE) VALUES 
('어린 왕자', '앙투안 드 생텍쥐페리', '황금가지', TO_DATE('2005-05-05', 'YYYY-MM-DD'), 10000);
INSERT INTO BOOK (TITLE, AUTHOR, PUBLISHER, PUBLISHER_DATE, PRICE) VALUES 
('죄와 벌', '표도르 도스토예프스키', '문예출판사', TO_DATE('2012-10-10', 'YYYY-MM-DD'), 18000);
INSERT INTO BOOK (TITLE, AUTHOR, PUBLISHER, PUBLISHER_DATE, PRICE) VALUES 
('사피엔스', '유발 하라리', '김영사', TO_DATE('2017-08-01', 'YYYY-MM-DD'), 22000);
INSERT INTO BOOK (TITLE, AUTHOR, PUBLISHER, PUBLISHER_DATE, PRICE) VALUES 
('총 균 쇠', '재레드 다이아몬드', '문학동네', TO_DATE('2011-11-11', 'YYYY-MM-DD'), 25000);
INSERT INTO BOOK (TITLE, AUTHOR, PUBLISHER, PUBLISHER_DATE, PRICE) VALUES 
('모모', '미하엘 엔데', '비룡소', TO_DATE('2009-02-20', 'YYYY-MM-DD'), 14000);
INSERT INTO BOOK (TITLE, AUTHOR, PUBLISHER, PUBLISHER_DATE, PRICE) VALUES 
('노르웨이의 숲', '무라카미 하루키', '민음사', TO_DATE('2013-07-07', 'YYYY-MM-DD'), 16000);
INSERT INTO BOOK (TITLE, AUTHOR, PUBLISHER, PUBLISHER_DATE, PRICE) VALUES 
('백년의 고독', '가브리엘 가르시아 마르케스', '열린책들', TO_DATE('2006-04-04', 'YYYY-MM-DD'), 19000);


COMMIT;

--DROP TABLE BOOK;

--쿼리문 errORA-00933: SQL 명령어가 올바르게 종료되지 않았습니다


                SELECT book_id,
                       title,
                       author,
                       TO_CHAR(publisher_date, 'YYYY-MM-DD') AS publisher_date,
                       price
                FROM book
                ORDER BY book_id;
                
                