--학생예제 student subject


CREATE TABLE subject(
    NO NUMBER NOT NULL,
    S_NUM CHAR(2),  --학과번호
    S_NAME VARCHAR2(80) NOT NULL,
    CONSTRAINT subject_no_pk PRIMARY KEY(no),
    CONSTRAINT subject_s_num_uk UNIQUE(s_num)
);
CREATE SEQUENCE subject_seq
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 99999
NOCYCLE
CACHE 2;
INSERT INTO subject(no,s_num,s_name) VALUES (subject_seq.NEXTVAL,'01','컴퓨터학과');
INSERT INTO subject(no,s_num,s_name) VALUES (subject_seq.NEXTVAL,'02','교육학과');
INSERT INTO subject(no,s_num,s_name) VALUES (subject_seq.NEXTVAL,'03','신문방송학과');
INSERT INTO subject(no,s_num,s_name) VALUES (subject_seq.NEXTVAL,'04','인터넷비즈니스학과');
INSERT INTO subject(no,s_num,s_name) VALUES (subject_seq.NEXTVAL,'05','기술경영과');

SELECT * FROM subject;

commit;




CREATE TABLE STUDENT(
    NO NUMBER GENERATED BY DEFAULT AS IDENTITY,
    SD_NUM CHAR(8) NOT NULL,
    SD_NAME NVARCHAR2(15) NOT NULL,
    SD_ID VARCHAR2(15) NOT NULL,
    SD_PASSWD VARCHAR2(15) NOT NULL,
    S_NUM CHAR(2) NOT NULL,  --학과번호
    SD_BIRTH DATE NOT NULL,
    SD_PHONE VARCHAR2(15) NOT NULL,
    SD_ADDRESS NVARCHAR2(100) NOT NULL,
    SD_EMAIL VARCHAR2(100) NOT NULL,
    SD_DATE DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT student_no_pk PRIMARY KEY(no),
    CONSTRAINT student_sd_num_uk UNIQUE(sd_num),
    CONSTRAINT student_id_pk UNIQUE(SD_ID),
    CONSTRAINT student_s_num_fk FOREIGN KEY (s_num) REFERENCES SUBJECT(s_num)
);
--INSERT INTO STUDENT(SD_NUM,SD_NAME,SD_ID,SD_PASSWD,S_NUM,SD_BIRTH,SD_PHONE,SD_ADDRESS,SD_EMAIL) VALUES 
--    (
--    '06010001',
--    '김정수',
--    'javajsp',
--    'java1234',
--    '01',
--    TO_DATE('19860424','YYYYMMDD'),
--    '01032789054',
--    '(03727) 서울 특별시 서문구 성산로 450-2',
--    'java12@naver.com'
--    )
--;
INSERT INTO STUDENT(SD_NUM,SD_NAME,SD_ID,SD_PASSWD,S_NUM,SD_BIRTH,SD_PHONE,SD_ADDRESS,SD_EMAIL) VALUES 
('06010001', '김정수', 'javajsp', 'java1234', '01', TO_DATE('19860424', 'YYYYMMDD'), '01032789054', '(03727) 서울 특별시 서문구 성산로 450-2', 'java12@naver.com');
INSERT INTO STUDENT(SD_NUM,SD_NAME,SD_ID,SD_PASSWD,S_NUM,SD_BIRTH,SD_PHONE,SD_ADDRESS,SD_EMAIL) VALUES 
('06010002', '이민지', 'minji02', 'pass2345', '02', TO_DATE('19920314', 'YYYYMMDD'), '01012345678', '(04515) 서울 특별시 동작구 상도로 10', 'minji02@gmail.com');
INSERT INTO STUDENT(SD_NUM,SD_NAME,SD_ID,SD_PASSWD,S_NUM,SD_BIRTH,SD_PHONE,SD_ADDRESS,SD_EMAIL) VALUES 
('06010003', '박철수', 'chulsoo03', 'abc9876', '03', TO_DATE('19891230', 'YYYYMMDD'), '01098765432', '(06123) 서울 특별시 강남구 테헤란로 123', 'chulsoo03@yahoo.com');
INSERT INTO STUDENT(SD_NUM,SD_NAME,SD_ID,SD_PASSWD,S_NUM,SD_BIRTH,SD_PHONE,SD_ADDRESS,SD_EMAIL) VALUES 
('06010004', '최나래', 'narae04', 'pw123456', '04', TO_DATE('19950721', 'YYYYMMDD'), '01055554444', '(02871) 서울특별시 마포구 월드컵로 77', 'narae04@naver.com');
INSERT INTO STUDENT(SD_NUM,SD_NAME,SD_ID,SD_PASSWD,S_NUM,SD_BIRTH,SD_PHONE,SD_ADDRESS,SD_EMAIL) VALUES 
('06010005', '정다은', 'daeun05', 'da1234', '05', TO_DATE('19901212', 'YYYYMMDD'), '01011112222', '(03123) 서울특별시 노원구 한글비석로 99', 'daeun05@hotmail.com');
INSERT INTO STUDENT(SD_NUM,SD_NAME,SD_ID,SD_PASSWD,S_NUM,SD_BIRTH,SD_PHONE,SD_ADDRESS,SD_EMAIL) VALUES 
('06010006', '한성우', 'sungwoo06', 'hsw9876', '01', TO_DATE('19881108', 'YYYYMMDD'), '01033334444', '(04021) 서울특별시 서대문구 신촌로 56', 'sungwoo06@gmail.com');
SELECT * FROM STUDENT;

desc subject;

--DROP TABLE subject;
--DROP SEQUENCE subject_seq;

SELECT * FROM tab;
SELECT * FROM subject;  //학과
SELECT * FROM student;  //학생
SELECT * FROM COURSE;      //과목
SELECT * FROM ENROLLMENT;  //수강

SELECT st.sd_num,st.sd_name,sj.s_num,sj.s_name
FROM student st JOIN subject sj on st.s_num = sj.s_num
;


COMMIT;
SELECT * FROM ENROLLMENT;  //수강


CREATE TABLE course (
no NUMBER NOT NULL,
c_num CHAR (7) NOT NULL,
c_name VARCHAR2 (80)NOT NULL,
c_credit NUMBER (2) NOT NULL,
c_section NCHAR(2) NOT NULL,
CONSTRAINT course_no_pk PRIMARY KEY (no),
CONSTRAINT course_c_num_uk UNIQUE (c_num),
CONSTRAINT course_c_credit_ck CHECK (c_credit BETWEEN 2 AND 4),
CONSTRAINT course_c_section_ck CHECK (c_section IN ('교양','일반','전공' ))
);
CREATE SEQUENCE course_seq
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 99999
NOCYCLE
CACHE 2;

--DROP TABLE Course;
--DROP SEQUENCE course_seq;

INSERT INTO Course (no, c_num, c_name, c_credit, c_section) VALUES (course_seq.NEXTVAL, 'UA04001', '대학영어', 2, '교양');
INSERT INTO course (no, c_num, c_name, c_credit, c_section) VALUES (course_seq.NEXTVAL, 'UA05001', '소프트웨어와 창의적 사고', 4, '교양');
INSERT INTO course (no, c_num, c_name, c_credit, c_section) VALUES (course_seq.NEXTVAL, 'UBB0001', '독서와 토론', 3, '교양');
INSERT INTO course (no, c_num, c_name, c_credit, c_section) VALUES (course_seq.NEXTVAL, 'UGG0010', '한국의 이해', 3, '일반');
INSERT INTO course (no, c_num, c_name, c_credit, c_section) VALUES (course_seq.NEXTVAL, 'UGG0031', '내아이디어로 창업하기', 4, '일반');
INSERT INTO Course (no, c_num, c_name, c_credit, c_section) VALUES (course_seq.NEXTVAL, 'UCR0001', '데이터베이스 설계와 구축', 4, '전공');
INSERT INTO Course (no, c_num, c_name, c_credit, c_section) VALUES (course_seq.NEXTVAL, 'UCR0002', '데이터분석', 4, '전공');


CREATE TABLE enrollment(
    NO NUMBER NOT NULL,
    e_year CHAR(4) NOT NULL,
    e_semester NVARCHAR2(4) NOT NULL,
    sd_num CHAR(8) NOT NULL,
    c_NuM CHAR(7) NOT NULL,         --과목
    e_grade NUMBER(2,1) NOT NULL,   --성적
    e_DATE DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT enrollment_no_pk PRIMARY KEY(no),
    CONSTRAINT enrollment_e_semester_ck CHECK (e_semester IN ('1학기','2학기','3학기' )),
    CONSTRAINT enrollment_e_grade_ck CHECK (e_grade BETWEEN 0 AND 4.5),
    CONSTRAINT enrollment_sd_num_fk FOREIGN KEY (sd_num) REFERENCES student(sd_num),
    CONSTRAINT enrollment_c_num_fk FOREIGN KEY (c_num) REFERENCES course(c_num)
);

CREATE SEQUENCE enrollment_seq
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 99999
NOCYCLE
CACHE 2;

--DROP TABLE enrollment;
--DROP SEQUENCE enrollment_seq;

INSERT INTO enrollment (no, e_year,e_semester, sd_num, c_num, e_grade) VALUES (enrollment_seq.NEXTVAL, '2004', '1학기', '06010001', 'UA05001', 4.0);
INSERT INTO enrollment (no, e_year,e_semester, sd_num, c_num, e_grade) VALUES (enrollment_seq.NEXTVAL, '2004', '1학기', '06010003', 'UBB0001', 3.8);
INSERT INTO enrollment (no, e_year,e_semester, sd_num, c_num, e_grade) VALUES (enrollment_seq.NEXTVAL, '2004', '1학기', '06010001', 'UCR0001', 4.3);
INSERT INTO enrollment (no, e_year,e_semester, sd_num, c_num, e_grade) VALUES (enrollment_seq.NEXTVAL, '2004', '1학기', '06010004', 'UGG0031', 3.6);



--명령의 133 행에서 시작하는 중 오류 발생 -
--INSERT INTO enrollment (no, e_year,e_semester, sd_num, c_num, e_grade) VALUES (enrollment_seq.NEXTVAL, '2004', '1학기', '08020001', 'UGG0031', 3.6)
--오류 보고 -
--ORA-02291: 무결성 제약조건(JAVAUSER.ENROLLMENT_SD_NUM_FK)이 위배되었습니다- 부모 키가 없습니다
